name: build

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'webrtc-sdk commit hash'
        default: 'm114_release'
        required: true


jobs:
  build-windows:
    defaults:
      run:
        working-directory: .\\build
    strategy:
      fail-fast: false
      matrix:
        name:
          - windows_x86_64
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Disk Cleanup
      run: |
        Get-PSDrive
        # Cache 済み Docker Image の削除
        # Clean unused docker images
        docker rmi $(docker images -q -a)
        # Android SDK の削除
        # Delete Android SDK
        Remove-Item -Recurse -Force $Env:ANDROID_HOME -ErrorAction Ignore
        Remove-Item -Recurse -Force $Env:ANDROID_NDK_HOME -ErrorAction Ignore
        # JVM の削除
        # Delete JVM
        Remove-Item -Recurse -Force $Env:JAVA_HOME_11_X64 -ErrorAction Ignore
        Remove-Item -Recurse -Force $Env:JAVA_HOME_8_X64 -ErrorAction Ignore
        Get-PSDrive
    - run: "& .\\build.${{ matrix.name }}.ps1 \"${{ github.event.inputs.commitHash }}\""
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webrtc.${{ matrix.name }}.bz2
        path: build\_package\${{ matrix.name }}\webrtc.tar.bz2
  build-macos:
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          # - macos_arm64
          - macos_x86_64
          # - ios
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 13.0
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
    - run: brew install ninja
    - run: ./build.${{ matrix.name }}.sh "${{ github.event.inputs.commitHash }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webrtc.${{ matrix.name }}.tar.bz2
        path: build/_package/${{ matrix.name }}/webrtc.tar.bz2
  build-linux:
    if: false  
    defaults:
      run:
        working-directory: ./build
    strategy:
      fail-fast: false
      matrix:
        name:
          # - raspberry-pi-os_armv6
          # - raspberry-pi-os_armv7
          # - raspberry-pi-os_armv8
          # - ubuntu-18.04_armv8
          # - ubuntu-20.04_armv8
          # - ubuntu-18.04_x86_64
          # - ubuntu-20.04_x86_64
          # - ubuntu-22.04_x86_64
          - android
          - android_prefixed
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v4
    - name: Disk Cleanup
      run: |
        df -h
        docker container prune -f
        docker image prune -a -f
        # 3.9GB
        sudo rm -rf /usr/local/share/boost
        # 17GB
        sudo rm -rf /usr/share/dotnet
        df -h
    - run: ./build.${{ matrix.name }}.sh "${{ github.event.inputs.commitHash }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webrtc.${{ matrix.name }}.tar.bz2
        path: build/_package/${{ matrix.name }}/webrtc.tar.bz2

